/**
 * Импорт юридических текстов (модалки agreement1–3) и cookies PNG с redbox.su
 * Запуск: node scripts/scrape-legal.mjs
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import * as cheerio from "cheerio";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const OUT_TS = path.join(ROOT, "lib/content/legal.generated.ts");
const COOKIES_OUT = path.join(ROOT, "public/legal/cookies.png");
const COOKIES_URL =
  "https://redbox.su/upload/politika-ispolzovanija-cookies-redbox.png";

/** Kraken: POST /bitrix/tools/kraken/ajax/agreemodal.php { formId: "1"|"2"|"3", site_id: "s1" } */
const DOCS = [
  {
    formId: "1",
    slug: "personal-data",
    title: "Обработка персональных данных",
    metaTitle: "Согласие на обработку персональных данных",
  },
  {
    formId: "2",
    slug: "privacy",
    title: "Политика конфиденциальности",
    metaTitle: "Политика конфиденциальности",
  },
  {
    formId: "3",
    slug: "offer",
    title: "Договор-оферта",
    metaTitle: "Договор-оферта",
  },
];

const AGREEMENT_URL = "https://redbox.su/bitrix/tools/kraken/ajax/agreemodal.php";
const SITE_ID = "s1";

function escape(str) {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
}

const SITE_HOST = "titlo.ru";
const LK_HOST = "cabinet.titlo.ru";
const SITE_EMAIL = "info@titlo.ru";

function normalizeLegalHtml(html) {
  return html
    .replace(/redbox\.su\.ru/gi, "redbox.su")
    .replace(/info@kargo24\.su/gi, SITE_EMAIL)
    .replace(/href="mailto:info@kargo24\.su"/gi, `href="mailto:${SITE_EMAIL}"`)
    .replace(
      /размещенный в сети Интернет по адресу redbox\.su, а также любые сайты в доменной зоне \*\.redbox\.su \(где \* - любое имя\)/gi,
      `размещённый в сети Интернет на сайте ${SITE_HOST} и в личном кабинете ${LK_HOST}, а также на любых поддоменах указанных доменов`,
    )
    .replace(/https:\/\/redbox\.su\/tarify\//gi, `https://${SITE_HOST}/tarify/`)
    .replace(/https:\/\/redbox\.su\//gi, `https://${SITE_HOST}/`)
    .replace(/https:\/\/redbox\.su/gi, `https://${SITE_HOST}`)
    .replace(/href="mailto:info@redbox\.su"/gi, `href="mailto:${SITE_EMAIL}"`)
    .replace(/info@redbox\.su/gi, SITE_EMAIL)
    .replace(/lk\.redbox\.su/gi, LK_HOST)
    .replace(/\*\.redbox\.su/gi, `*.${SITE_HOST} и *.${LK_HOST}`)
    .replace(/redbox\.su/gi, SITE_HOST);
}

function cleanHtml($, root) {
  root.find("script, style, iframe").remove();
  root.find("[class*='close'], .modal-header button").remove();
  let html = root.html()?.trim() ?? "";
  html = html
    .replace(/\s+/g, " ")
    .replace(/>\s+</g, "><")
    .replace(/RedBox/g, "Титло");
  return normalizeLegalHtml(html);
}

async function fetchBinary(url) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${url} → ${res.status}`);
  return Buffer.from(await res.arrayBuffer());
}

function extractAgreementHtml(html) {
  const $ = cheerio.load(html);
  const body = $(".content-in.text-content").first();
  if (!body.length) return null;
  return cleanHtml($, body);
}

async function fetchAgreement(formId) {
  const body = new URLSearchParams({ formId, site_id: SITE_ID });
  const res = await fetch(AGREEMENT_URL, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body,
  });
  if (!res.ok) throw new Error(`agreement ${formId} → ${res.status}`);
  return res.text();
}

async function main() {
  const docs = [];
  for (const spec of DOCS) {
    console.log(`Fetching agreement ${spec.formId}…`);
    const html = await fetchAgreement(spec.formId);
    const bodyHtml = extractAgreementHtml(html);
    if (!bodyHtml) {
      console.warn(`Missing content for formId=${spec.formId}`);
      continue;
    }
    docs.push({ ...spec, bodyHtml });
    console.log(`  ${spec.slug}: ${bodyHtml.length} chars`);
  }

  if (docs.length !== DOCS.length) {
    throw new Error("Not all legal modals were extracted");
  }

  fs.mkdirSync(path.dirname(COOKIES_OUT), { recursive: true });
  console.log("Downloading cookies policy PNG…");
  const png = await fetchBinary(COOKIES_URL);
  fs.writeFileSync(COOKIES_OUT, png);

  const entries = docs
    .map(
      (d) => `  {
    slug: ${JSON.stringify(d.slug)},
    title: ${JSON.stringify(d.title)},
    metaTitle: ${JSON.stringify(d.metaTitle)},
    bodyHtml: \`${escape(d.bodyHtml)}\`,
  }`,
    )
    .join(",\n");

  const ts = `/** AUTO-GENERATED by scripts/scrape-legal.mjs — do not edit by hand */
export type LegalDoc = {
  slug: string;
  title: string;
  metaTitle: string;
  bodyHtml: string;
};

export const LEGAL_DOCS: LegalDoc[] = [
${entries}
];
`;

  fs.writeFileSync(OUT_TS, ts);
  console.log(`Wrote ${OUT_TS} and ${COOKIES_OUT}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
